default: &default
  adapter: postgresql
  encoding: unicode
  pool: 1000

development:
  <<: *default
  database: development
  username: <%= Rails.application.credentials.PG_DB_USER %>
  password: <%= Rails.application.credentials.PG_DB_PASS %>


production:
  <<: *default
  database: <%= Rails.application.credentials.PG_DB_NAME %>
  username: <%= Rails.application.credentials.PG_DB_USER %>
  password: <%= Rails.application.credentials.PG_DB_PASS %>
  host: <%= Rails.application.credentials.PG_DB_HOST %>

test:
  <<: *default
  database: test<%= ENV['TEST_ENV_NUMBER'] %>
  username: <%= Rails.application.credentials.TEST_DB_USER %>
  password: <%= Rails.application.credentials.TEST_DB_PASS %>
